export const languages = [
  { value: "eng", text: "English" },
  { value: "por", text: "Portuguese" },
  { value: "fra", text: "French" },
  { value: "osd", text: "Orientation and Script Detection" },
  { value: "chi_sim", text: "Chinese (Simplified)" },
  { value: "spa", text: "Spanish" },
  { value: "deu", text: "German" },
  { value: "chi_tra", text: "Chinese (Traditional)" },
  { value: "heb", text: "Hebrew" },
  { value: "kor", text: "Korean" },
  { value: "jpn", text: "Japanese" },
  { value: "rus", text: "Russian" },
  { value: "nld", text: "Dutch" },
  { value: "hin", text: "Hindi" },
  { value: "ita", text: "Italian" },
  { value: "jpn_vert", text: "Japanese (Vertical)" },
  { value: "pol", text: "Polish" },
  { value: "ron", text: "Romanian" },
  { value: "mar", text: "Marathi" },
  { value: "ukr", text: "Ukrainian" },
  { value: "mal", text: "Malayalam" },
  { value: "tam", text: "Tamil" },
  { value: "guj", text: "Gujarati" },
  { value: "tha", text: "Thai" },
  { value: "kan", text: "Kannada" },
  { value: "vie", text: "Vietnamese" },
  { value: "tel", text: "Telugu" },
  { value: "swe", text: "Swedish" },
  { value: "tur", text: "Turkish" },
  { value: "nor", text: "Norwegian" },
  { value: "ces", text: "Czech" },
  { value: "ben", text: "Bengali" },
  { value: "pan", text: "Punjabi" },
  { value: "equ", text: "Math / Equation Detection" },
  { value: "ell", text: "Greek" },
  { value: "bul", text: "Bulgarian" },
  { value: "lat", text: "Latin" },
  { value: "kur", text: "Kurdish" },
  { value: "ori", text: "Odia" },
  { value: "kat", text: "Georgian" },
  { value: "amh", text: "Amharic" },
  { value: "kaz", text: "Kazakh" },
  { value: "cat", text: "Catalan" },
  { value: "nep", text: "Nepali" },
  { value: "urd", text: "Urdu" },
  { value: "khm", text: "Khmer" },
  { value: "dan", text: "Danish" },
  { value: "chi_sim_vert", text: "Chinese (Simplified, Vertical)" },
  { value: "uzb", text: "Uzbek (Latin)" },
  { value: "slv", text: "Slovenian" },
  { value: "mkd", text: "Macedonian" },
  { value: "tgl", text: "Tagalog" },
  { value: "srp", text: "Serbian (Cyrillic)" },
  { value: "hrv", text: "Croatian" },
  { value: "tir", text: "Tigrinya" },
  { value: "syr", text: "Syriac" },
  { value: "lao", text: "Lao" },
  { value: "fin", text: "Finnish" },
  { value: "est", text: "Estonian" },
  { value: "bos", text: "Bosnian" },
  { value: "uig", text: "Uyghur" },
  { value: "sin", text: "Sinhala" },
  { value: "hye", text: "Armenian" },
  { value: "eus", text: "Basque" },
  { value: "sqi", text: "Albanian" },
  { value: "isl", text: "Icelandic" },
  { value: "bel", text: "Belarusian" },
  { value: "aze", text: "Azerbaijani (Latin)" },
  { value: "pus", text: "Pashto" },
  { value: "oci", text: "Occitan" },
  { value: "lit", text: "Lithuanian" },
  { value: "jav", text: "Javanese" },
  { value: "hun", text: "Hungarian" },
  { value: "grc", text: "Ancient Greek" },
  { value: "gle", text: "Irish" },
  { value: "frm", text: "Middle French" },
  { value: "afr", text: "Afrikaans" },
  { value: "uzb_cyrl", text: "Uzbek (Cyrillic)" },
  { value: "spa_old", text: "Old Spanish" },
  { value: "snd", text: "Sindhi" },
  { value: "mya", text: "Burmese" },
  { value: "iku", text: "Inuktitut" },
  { value: "fil", text: "Filipino" },
  { value: "fas", text: "Persian" },
  { value: "fao", text: "Faroese" },
  { value: "dzo", text: "Dzongkha" },
  { value: "cym", text: "Welsh" },
  { value: "aze_cyrl", text: "Azerbaijani (Cyrillic)" },
  { value: "ind", text: "Indonesian" },
  { value: "ara", text: "Arabic" },
  { value: "yid", text: "Yiddish" },
  { value: "ton", text: "Tongan" },
  { value: "tgk", text: "Tajik" },
  { value: "srp_latn", text: "Serbian (Latin)" },
  { value: "slk_frak", text: "Slovak (Fraktur)" },
  { value: "slk", text: "Slovak" },
  { value: "san", text: "Sanskrit" },
  { value: "msa", text: "Malay" },
  { value: "mri", text: "Maori" },
  { value: "mlt", text: "Maltese" },
  { value: "lav", text: "Latvian" },
  { value: "kur_ara", text: "Kurdish (Arabic)" },
  { value: "kor_vert", text: "Korean (Vertical)" },
  { value: "kmr", text: "Kurmanji" },
  { value: "kir", text: "Kyrgyz" },
  { value: "hat", text: "Haitian Creole" },
  { value: "glg", text: "Galician" },
  { value: "fry", text: "Frisian" },
  { value: "epo", text: "Esperanto" },
  { value: "div", text: "Divehi" },
  { value: "chr", text: "Cherokee" },
  { value: "bod", text: "Tibetan" },
  { value: "asm", text: "Assamese" },
  { value: "yor", text: "Yoruba" },
  { value: "tat", text: "Tatar" },
  { value: "sun", text: "Sundanese" },
  { value: "occ", text: "Occitan (alternative)" },
  { value: "mon", text: "Mongolian" },
  { value: "ita_old", text: "Old Italian" },
  { value: "gla", text: "Scottish Gaelic" },
  { value: "frk", text: "Frankish" },
  { value: "enm", text: "Middle English" },
  { value: "deu_frak", text: "German (Fraktur)" },
  { value: "dan_frak", text: "Danish (Fraktur)" },
  { value: "chi_tra_vert", text: "Chinese (Traditional, Vertical)" },
  { value: "ceb", text: "Cebuano" },
  { value: "bre", text: "Breton" },
  { value: "swa", text: "Swahili" },
  { value: "que", text: "Quechua" },
  { value: "ltz", text: "Luxembourgish" },
  { value: "kat_old", text: "Old Georgian" },
  { value: "cos", text: "Corsican" },
];
